/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.product.*

class App {

}

fun main() {
    var p1 = Product()

    try {
        // This is how you invoke setter in kotlin
        p1.price = 150.0
    }
    catch (e : Exception){
        println ("ERROR:: ${e.message}")
    }
    finally {
        p1.infos()
    }
}
