/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAValidProduct(){
        assertNotNull(App().p1, "app should have a product")
    }
}
